language: node_js
node_js:
  - "10"
script:
  - npm install
  - npm run build
  - cd dist && echo 'sotap.dev' > CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: true
  on:
    branch: deploy
